### ISSUE TITLE
size and floating

### ISSUE THREAD

**Issue by carepack** [gawen947/i3-quaketerm#1]
Hi and thx for this solution. Fits perfectly my needs. I have some question.
This:
for_window [instance="i3-quaketerm"] border none floating enable
How should the terminal look like? I'm asking because I got different results
1. https://imgur.com/a/YBYzc
2. https://imgur.com/a/oKyVU

So my question is, if its possible to get the terminal like in the first picture? 
Another question would be about the ratio option. How do I achieve to get the terminal to not take the full width? If I change the ration only the height is gonna be changed.

Tank you!

**Comment by gawen947** [comment]
The ratio option is the height as a ratio of focused workspace height. The name was probably misleading. So there was no way to adjust width and offset as in the first picture... until now.

I just replaced the ratio option with the width, height and offset options.
Pull again and tell me if that works for you.

**Comment by gawen947** [comment]
Beside I don't know if offset would be better expressed as a ratio or in pixels.
You use this, so you probably know better, you can tell me what you'd prefer ;)

**Comment by carepack** [comment]
Hi, width is working fine and also offset. I prefer the pixel annotation rather than ratio in case of offset.
Big thx! Fits perfect.

Another thing is I noticed:
opacity-rule = [ "95:class_g='i3-quaketerm'" ];

This option doesn't take effect. The strange thing is, opacity for URxvt affects all urxvt terminals except: i3-queketerm and all urxvt terminals started with the -name option

**Comment by gawen947** [comment]
`i3-quaketerm -w 0.8 -o 25 -p bottom`

As for transparency, did you use another name with `i3-quaketerm --name i3-something`? In that case the compton rule needs to be adapted. Otherwise check the class of the terminal created by i3-quaketerm with `xprop | grep "WM_CLASS"`.

**Comment by carepack** [comment]
the wm string is
WM_CLASS(STRING) = "i3-quaketerm", "URxvt"
like it should be. compton.conf has
opacity-rule = [ "60:class_g='i3-quaketerm'" ];

but i3-quaketerm is not affcted through this. i3-quakterm is the instance name and the class is URxvt. 
so this
opacity-rule = [ "60:class_g = 'URxvt'" ];
should affect all urxvt windows but it doesn't. i3-quaketerm and urxvt's started with the name options won't get recognized and don't receive transparency.

**Comment by gawen947** [comment]
Try this:

[ "60:name='i3-quaketerm'" ];

**Comment by carepack** [comment]
sorry, also not working. In my .Xresources I enabled real transparency via 
urxvt.depth: 32
urxvt.background: rgba:0000/0000/0200/c800
I don't why it won't get recognized. Is it working for you? Thanks for the effort

I start i3-quaketerm via i3 keybinding:
bindsym F12 exec --no-startup-id i3-quaketerm -p bottom -t urxvtc -w 0.75 -o 50 -H


EDIT:
Sorry, it's working now. I added multiple opacity lines in compton.conf. With the followng line it's working for quaketerm but not my named urxvt terminals. 
`opacity-rule = [ "60:class_g = 'URxvt'","60:name='i3-quaketerm'","60:name='ranger'","60:name='neofetch'" ];`
I have to investigate further. big thx again.

**Comment by gawen947** [comment]
Strange, it works for me with urxvt v9.22 and compton-20160907_2 on FreeBSD, also with client/daemon and your Xresources. If you cannot get transparency to work manually with urxvt -name, that's probably a urxvt/compton problem. So I couldn't be of much more help there, sorry...

As a workaround I'd suggest you use another terminal such as xterm, mlterm or sakura, may be just for i3-quaketerm. The three are working with compton, at least for me.

Closing this since the original issue was fixed. If need be, reopen a new issue.
